### ISSUE TITLE
Build breaks on 8.4

### ISSUE THREAD

**Issue by tomjaguarpaw** [twanvl/multiset#30]
Any chance we can get a version of this that works on 8.4?  Specifically, it needs a `Semigroup` instance.

**Comment by tomjaguarpaw** [comment]
This PR fixes it https://github.com/twanvl/multiset/pull/29

**Comment by twanvl** [comment]
I have merged #29, and uploaded it to Hackage.

**Comment by tomjaguarpaw** [comment]
Thanks very much!
