### ISSUE TITLE
Wish: Make MultiSet instance of NFData

### ISSUE THREAD

**Issue by pjljvandelaar** [twanvl/multiset#31]
I would like to use `MultiSet` inside a data structure that has
`deriving (Eq,Ord,Read,Show, Generic, NFData, Data)`.
This lead to an error `* No instance for (NFData (MultiSet.MultiSet BExpr))`
Could `MultiSet` just like `Set` be derived from NFData?

**Comment by twanvl** [comment]
I have added the instance.
